- name: Enable TLS now
  ansible.builtin.command: /usr/local/bin/hubctl internaltls server
  when: ca_certs == "supplied" or ca_certs == "selfsigned"
- name: Run ldapsync
  ansible.builtin.command: /usr/local/bin/hubctl ldapsync
  when: ldap_enabled == "true"
- name: Run demo deployment
  ansible.builtin.command: /usr/local/bin/hubctl demo deployment
- name: Enable hub
  ansible.builtin.command: /usr/local/bin/hubctl service enable
- name: Start hub
  ansible.builtin.command: /usr/local/bin/hubctl service start

